### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Staegrin** [KidsDontPlay/Furnus#1]
Update furnus to 1.2 and removed my config then started up the game. Crashed before reaching the start screen.

crashlog:
https://gist.github.com/Staegrin/f2ce8964169fd5120aac
fml-client-latest:
https://gist.github.com/Staegrin/c767899abe1a2706c1bc

**Comment by accessdenied0** [comment]
Hey @MrRiegel, @Staegrin,

Sorry to put my error here but,
I think I got the [same Issue](http://pastebin.com/VJmf914m). In my case the Game doesn't crashed, it simply stop loading.

access_denied

**Comment by accessdenied0** [comment]
Hey @MrRiegel,

thank you very much for this quick fix, but can you provide the fixed file for us? Or you just want to add something for a further release?

access_denied

**Comment by KidsDontPlay** [comment]
immediately

**Comment by accessdenied0** [comment]
Thank you a lot! I really like your mod. I'm happy it is working again.
