### ISSUE TITLE
[1.9.4] The One Probe Support/RF Behavior

### ISSUE THREAD

**Issue by Mohron** [KidsDontPlay/Furnus#10]
Version: Furnus-1.9.4-1.81.jar
TOP: theoneprobe-1.9.4-1.0.10.jar

When RF support is enabled for Furnus and TOP is installed the TOP RF display gets weird and overflows (see Screenshot). I'm not sure if you've added TOP support or if TOP is just displaying the information it can without api integration.  Either way Furnus is the only mod I've seen this issue with thus-far. Also it some times shows negative RF.

Most machines with RF support hold a max amount of RF which can be kept filled if power is available. The RF for Furnus behaves like fuel going up and down as it burns through the entire available fuel before adding more. This is probably why there is weird behavior with other mods.

![Screenshot](https://s31.postimg.org/wy5ibpsvv/Furnus_RF.png) ![Screenshot2](https://s32.postimg.org/wcrm02ned/Furnus_Neg_RF.png)

**Comment by KidsDontPlay** [comment]
Yeah, some parts of the code are not that good.
I have to rewrite a bunch of code
