### ISSUE TITLE
[Suggestion] RF/tick Tooltip

### ISSUE THREAD

**Issue by Mohron** [KidsDontPlay/Furnus#11]
Would it be possible to have a tooltip, possibly when you hover over the fuel indicator, that shows how much RF/tick the machine consumes with the current upgrades? It might also be nice to be able to see the current processing time of a single operation.

**Comment by KidsDontPlay** [comment]
The Furnus doesn't consume RF each Tick.
If the furnus is out of fuel it consumes RF from internal storage (max. 40.000) and adds as much fuel as an ordinary coal would add

**Comment by Mohron** [comment]
Well is there a way that you can tell the user how much RF/fuel the machine will require per operation? Would be nice to have it available instead of having to try and calculate it manually.
