### ISSUE TITLE
Wireless RF heating coil issue

### ISSUE THREAD

**Issue by misterfixit** [KidsDontPlay/Furnus#13]
The wireless RF Heating Coil from extra utilities 2 doesn't stay inside either the pulvus or furnus.

**Comment by KidsDontPlay** [comment]
For me it works without problems

**Comment by misterfixit** [comment]
I'm using forge 2166 if that helps

**Comment by KidsDontPlay** [comment]
what do you mean by 'doesn't stay'? Does the coil just disappear?

**Comment by misterfixit** [comment]
Well shift clicking doesn't work at all and placing the coil in there it
just pops out in world after leaving the gui

**Comment by KidsDontPlay** [comment]
sounds weird. shift clicking works fine too. do normal coal or wood work?

**Comment by misterfixit** [comment]
Yup "normal" burnables worked just fine

**Comment by misterfixit** [comment]
Furnus-1.10.2-1.83.jar
extrautils2-1.10.2-1.1.1.jar
Forge 12.18.2.2166
Forgot to add the versions

**Comment by KidsDontPlay** [comment]
do you play in multiplayer?

**Comment by misterfixit** [comment]
Yes

**Comment by KidsDontPlay** [comment]
thats not my fault. you need a wireless RF battery

**Comment by misterfixit** [comment]
Hmm swear I had one thanks for the help
