### ISSUE TITLE
crash version 1.9 for mc 1.10.2

### ISSUE THREAD

**Issue by Serico86** [KidsDontPlay/Furnus#14]
i updated the mod and i have a crash report (for now i rollback to previous version)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  dsurroundcore (DynamicSurroundings-3.1.0.0BETA.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.6r.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 12/14/16 10:25 PM
Description: Ticking player

java.lang.AbstractMethodError: mrriegel.limelib.tile.CommonTileInventory.func_70300_a(Lnet/minecraft/entity/player/EntityPlayer;)Z
	at mrriegel.limelib.gui.CommonContainerTileInventory.func_75145_c(CommonContainerTileInventory.java:29)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:256)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:649)
	at net.minecraft.world.World.func_72939_s(World.java:1726)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mrriegel.limelib.gui.CommonContainerTileInventory.func_75145_c(CommonContainerTileInventory.java:29)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:256)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 468
	Entity Name: D4R10
	Entity's Exact location: 189.98, 61.63, 127.70
	Entity's Block location: World: (189,61,127), Chunk: (at 13,3,15 in 11,7; contains blocks 176,0,112 to 191,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:649)
	at net.minecraft.world.World.func_72939_s(World.java:1726)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: Adventure 1_10_2
	All players: 1 total; [EntityPlayerMP['D4R10'/468, l='Adventure 1_10_2', x=189.98, y=61.63, z=127.70]]
	Chunk stats: ServerChunkCache: 961 Drop: 0
	Level seed: 5828561829488234833
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (187,64,143), Chunk: (at 11,4,15 in 11,8; contains blocks 176,0,128 to 191,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1335356 game time, 1600620 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 13469 (now: false), thunder time: 127735 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1809128144 bytes (1725 MB) / 4040163328 bytes (3853 MB) up to 4660396032 bytes (4444 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx5000m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.2.163} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.163-universal.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.3.0} [InfinityLib] (infinitylib-0.3.0.jar) 
	UCHIJAAAA	agricraft{2.0.0-i0.3.0-a3} [AgriCraft] (agricraft-2.0.0-i0.3.0-a3.jar) 
	UCHIJAAAA	JEI{3.13.6.391} [Just Enough Items] (jei_1.10.2-3.13.6.391.jar) 
	UCHIJAAAA	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.3.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCHIJAAAA	bdlib{1.12.2.19} [BD Lib] (bdlib-1.12.2.19-mc1.10.2.jar) 
	UCHIJAAAA	betterbuilderswands{0.7.0} [Better Builder's Wands] (BetterBuildersWands-0.7.0-1.10r148+5479134.jar) 
	UCHIJAAAA	blockdrops{1.1.0} [Block Drops] (BlockDrops-1.10.2-1.1.0.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9.4.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	covers{0.4.1.14} [Simple Covers] (covers-0.4.1.14-mc1.10.2.jar) 
	UCHIJAAAA	craftingcraft{4.1.9} [CraftingCraft] (CraftingCraft_1.10.2-4.1.9.jar) 
	UCHIJAAAA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAA	cxlibrary{1.2.3} [CXLibrary] (cxlibrary-1.10.2-1.2.3.jar) 
	UCHIJAAAA	dsurround{3.1.0.0BETA} [Dynamic Surroundings] (DynamicSurroundings-3.1.0.0BETA.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.141_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.141_beta.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAA	engineersworkshop{1.0.0-1.10.2} [Engineers Workshop] (EngineersWorkshop-1.0.4-1.10.2.jar) 
	UCHIJAAAA	extratweaker{0.3} [ExtraTweaker] (ExtraTweaker-1.9.4-0.3.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3a.jar) 
	UCHIJAAAA	ezstorage{2.2.6} [EZStorage 2] (ezstorage-2.2.6.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	foamfix{0.4.0a} [FoamFix] (foamfix-0.4.0a-law.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.2.2.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.2.2.jar) 
	UCHIJAAAA	limelib{1.3.5} [LimeLib] (limelib-1.10.2-1.3.5.jar) 
	UCHIJAAAA	furnus{1.9} [Furnus] (furnus-1.10.2-1.9.jar) 
	UCHIJAAAA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJAAAA	hammercore{1.1.8} [Hammer Core] (HammerCore_1.10.2-1.1.8.jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJAAAA	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJAAAA	immersiveengineering{0.10-53} [Immersive Engineering] (ImmersiveEngineering-0.10-53.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	InGameInfoXML{2.8.1.89} [InGame Info XML] (InGameInfoXML-1.10.2-2.8.1.89-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	itemscroller{0.8.0} [Item Scroller] (itemscroller-1.10.2-0.8.0.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJAAAA	jet_packs{1.0.0} [Just JetPacks] (Just-Jetpacks-1.10.2-1.0.0.jar) 
	UCHIJAAAA	je_calculation{1.10.2-2.2.2} [Just Enough Calculation] (JustEnoughCalculation-1.10.2-2.2.2.jar) 
	UCHIJAAAA	jeresources{0.5.7.96} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.96.jar) 
	UCHIJAAAA	jet{2.1.39} [JustEnoughTooltips] (JustEnoughTooltips-1.10.2-2.1.39.jar) 
	UCHIJAAAA	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCHIJAAAA	mobamputation{6.0.0} [MobAmputation] (MobAmputation-1.10.2-6.0.0.jar) 
	UCHIJAAAA	mobdismemberment{6.0.0} [MobDismemberment] (MobDismemberment-1.10.2-6.0.0.jar) 
	UCHIJAAAA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.9-1.1.2.jar) 
	UCHIJAAAA	nmsot{1.1.9-mc1.10.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.9-mc1.10.2.jar) 
	UCHIJAAAA	ObsidianPlates{1.1.1} [Obsidian Plates] (ObsidianPlates-1.1.1_1.9.4.jar) 
	UCHIJAAAA	getalltheseeds{1.9.4-1.10.2a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.9.4-1.10.2a.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.12} [Storage Drawers] (StorageDrawers-1.10.2-3.5.12.jar) 
	UCHIJAAAA	refinedstorage{1.2.11} [Refined Storage] (refinedstorage-1.2.11.jar) 
	UCHIJAAAA	rftools{5.71} [RFTools] (rftools-1.1x-5.71.jar) 
	UCHIJAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAA	simplyjetpacks{2.0.3.23} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.0.3.23.jar) 
	UCHIJAAAA	SolarFluxReborn{1.6r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-1.6r.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHIJAAAA	substratum{1.8.2.1} [Substratum] (Substratum-1.10.2-1.8.2.1.jar) 
	UCHIJAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCHIJAAAA	VeinMiner{0.35.1_1.9-f4a2566} [Vein Miner] (VeinMiner-0.35.1-1.9r584+f4a2566.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.1_1.9-f4a2566} [Mod Support] (VeinMiner-0.35.1-1.9r584+f4a2566.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
dsurroundcore (DynamicSurroundings-3.1.0.0BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  cubex2.cxlibrary.CoreModTransformer
SFRCore (SolarFluxReborn_1.10.2-1.6r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AgriCraftAPI (1.0) from agricraft-2.0.0-i0.3.0-a3.jar
		* AppleCoreAPI (2.2.0) from AppleCore-mc1.10.2-2.1.0.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.9.4-1.0.1.1.jar
		* CoFHAPI (1.8.9R1.2.0B1) from limelib-1.10.2-1.3.5.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from EngineersWorkshop-1.0.4-1.10.2.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.1.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.53.jar
		* compactstorage (v2.0.0a) from compactstorage-2.1-1.9.4.jar
		* compatlayer (0.1.3) from compatlayer-1.10-0.1.3.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* iChunUtil API (1.0.0) from iChunUtil-1.10.2-6.1.0.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-53.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-53.jar
		* jeresources|API (0.5.7.96) from JustEnoughResources-1.10.2-0.5.7.96.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.3.2.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.6.391.jar
		* mcjtylib_ng (2.3.1) from mcjtylib-1.1x-2.3.1.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.10.2-2.6.7-48.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* VeinMinerApi (0.3) from VeinMiner-0.35.1-1.9r584+f4a2566.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/D:/ftb/MultiMC-orig/instances/Adventure%201.10/minecraft/mods/SolarFluxReborn_1.10.2-1.6r.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['D4R10'/468, l='Adventure 1_10_2', x=189.98, y=61.63, z=127.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 15
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4425
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by BakermanLP** [comment]
Got the same error. Here is my crashlog: http://paste.ubuntu.com/23632714/
