### ISSUE TITLE
Cannot access pulvus or furnus gui

### ISSUE THREAD

**Issue by misterfixit** [KidsDontPlay/Furnus#15]
Right clicking doesn't work to access the inventory, currently placed furnus/pulvus and newly created ones as well. 
Furnus verion 1.10.2-1.91
Limelib version 1.10.2-1.3.3
forge version 12.18.2.2179

**Comment by KidsDontPlay** [comment]
you dare to open an issue without using latest limelib version?

**Comment by misterfixit** [comment]
Rip I know exactly how I managed that, damnit I'll close it for now and re open when tested properly
