### ISSUE TITLE
pulvus recipe not working (furnus 1.11.2-1.91)

### ISSUE THREAD

**Issue by SDUBZ** [KidsDontPlay/Furnus#17]
forge: 1.11.2-2255
furnus: 1.11.2-1.91
exparvis: exparvis-1.11-0.3.0
recipe trying to get working with pulvus
{
    "inputItem": "exparvis:nuggetore_gravel_gold:1",
    "outputItem": "neotech:dustgold:2",
    "experience": 0.3
  },
  {
    "inputItem": "exparvis:nuggetore_gravel_iron:1",
    "outputItem": "neotech:dustiron:2",
    "experience": 0.3
  }

**Comment by KidsDontPlay** [comment]
you used wrong syntax.
thats correct:
```
    {
        "inputItem": "exparvis:nuggetore_gravel_gold:0:1",
        "outputItem": "neotech:dustgold:0:2",
        "experience": 0.3
    },
    {
        "inputItem": "exparvis:nuggetore_gravel_iron:0:1",
        "outputItem": "neotech:dustiron:0:2",
        "experience": 0.3
    }
```

I would recommend this:
```
    {
        "inputItem": "exparvis:nuggetore_gravel_gold:0:1",
        "outputItem": "dustGold:2",
        "experience": 0.3
    },
    {
        "inputItem": "exparvis:nuggetore_gravel_iron:0:1",
        "outputItem": "dustIron:2",
        "experience": 0.3
    }
```
that would (probably) use dusts from this mod

**Comment by Darkosto** [comment]
I'm still a little confused on the syntax. I can't find anything that explains some of the lines. For example, why do some lines have ":0:1"? What exact information is needed after the item ID's?

Thank you,
Darkosto

**Comment by KidsDontPlay** [comment]
`modid:itemname:metadata:amount`
-1 for any metadata.
for oredict names metadata is not necessary

**Comment by Darkosto** [comment]
Got it! Thank you!!
