### ISSUE TITLE
Glow stone dupe

### ISSUE THREAD

**Issue by MarkSzita** [KidsDontPlay/Furnus#19]
You should blacklist glowstone from the pulvus. with the bonus upgrades you can pump glow stone blocks in, crush, craft and repeat. getting bonus glow stone in return.

**Comment by KidsDontPlay** [comment]
You're right. you can dupe glowstone. but it's expensive.
I tested it with 8 bonus upgrades and 8 efficiency upgrades and I needed 20 pieces of coal to turn 16 glowstone blocks into 32.
