### ISSUE TITLE
Certain ores can't be put in the pulvus

### ISSUE THREAD

**Issue by Staegrin** [KidsDontPlay/Furnus#2]
I noticed this when Forestry Copper and Tin ores were accepted by the pulvus while other mods' versions were not. So I did some testing to see which ores were accepted and which weren't.

List of ores that aren't accepted by the pulvus:
all gravel ores from Tinker's construct;
Non Forestry tin and copper ores
Immersive engineering nickel silver lead ores
Applied energistics charged certus quartz ore
Atum gold and iron ores 
Blue Power silver sapphire ruby amethyst ores
None of the dense ores from the dense ores mod
None of the ex-nihilo ores

**Comment by KidsDontPlay** [comment]
Thanks for reporting.
I'm an idiot. I added only one of each ore to the recipes instead of any.
So copper, tin, silver, lead, etc should be fixed.
I added dense ores and gems too.
You may add certus quartz manually to json file
