### ISSUE TITLE
[1.11.2-1.92] Dupe while breaking furnus

### ISSUE THREAD

**Issue by kreezxil** [KidsDontPlay/Furnus#20]
There is no crash report, I tested this with Forge build 2282 plus Furnus and JEI.

https://youtu.be/SBfLknlHa68 <-- demonstration

**Comment by KidsDontPlay** [comment]
<del>which limelib version do you use?</del>
that's a bug in limelib 1.5.3.
you may try 1.5.2

**Comment by kreezxil** [comment]
I'm using 1.11.2-1.5.3, I use the Curse Launcher so it keeps things current
for me.

**Comment by kreezxil** [comment]
this issue has returned in version 1.11.2 - 1.93 I haven't tested it with the furnus, but it is happening with the pulvus. Also using forge build 2311

**Comment by KidsDontPlay** [comment]
latest limelib version?

**Comment by kreezxil** [comment]
Oh right I did update to it. So frustrating to have to remember to use the
older one. Maybe you should archive the bugged version.

**Comment by kreezxil** [comment]
Oh, yeah, hadn't really had my coffee yet. The version used in this last duping was 1.54. I'm reverting to 1.52 now.

**Comment by kreezxil** [comment]
i deprecated to 1.52 the dupe is still ocurring, has to be forge related, my forge is now on build 2314.

**Comment by kreezxil** [comment]
I'm looking at your limelib and have a couple of questions.

In the file: https://github.com/MrRiegel/LimeLib/blob/1.11/src/main/java/mrriegel/limelib/block/CommonBlockContainer.java

The function breakBlock starting at line 44 appears to do the same thing as the function onBlockHarvested at line 117. Immediately what comes to mind is that Minecraft will hit both of those when I break my block and create a double.

Also in the function breakBlock you don't call the super as other mods in 1.11.2 do. For example in Better With Mods, the Steel Anvil which also spews it's contents into the world and then itself to the world, https://github.com/BeetoGuy/BetterWithMods/blob/1.11/src/main/java/betterwithmods/common/blocks/BlockSteelAnvil.java lines 110 to 115. On 114 it calls the super. 

If you search the better with mods repository for onBlockHarvested there are no results returned. My money is on that function causing the duping.

**Comment by KidsDontPlay** [comment]
in line 117 it drops the furnus, in line 44 it drops the content of the furnus.
`super.breakBlock()` just removes the tile entity. I do it in line 49.

I need to override `onBlockHarvested()` to drop the block when the tile entity wasn't removed yet. 

I tested it with only limelib 1.5.4, furnus 1.93 and forge 13.20.0.2314 installed and I cannot reproduce your bug. Do you use a normal pickaxe?

**Comment by kreezxil** [comment]
I found it! It's an incompatibility with MultiMine by AtomicStryker. Weird why no other blocks from other mods duplicate in conjunction with his mod. Multimine holds the state of the blocks breakage, so that you can come back to breaking it later without losing your progress in breaking it. Also useful for multiplayer so that more than one player can help break blocks even faster than if one were doing all the work. He's on github so I shall open a ticket there and cross reference this thread.
