### ISSUE TITLE
Dupe bug.

### ISSUE THREAD

**Issue by Buster5265** [KidsDontPlay/Furnus#25]
If I have an ingot/dust in my inventory and I right click the same ingot/dust (doesn't matter if I hold shift or not between clicks or if I open/close the GUI) out of a pulvus or a furnus, instead of adding 1 to my items it turns it in to a stack.
edit - this also happens with placing items in to a Furnus, if there is already 1 dust waiting to be processed, and I shift click one more in the stack in the Furnus the stack to be processed becomes 64.

LimeLib 1.12-1.7.1
Furnus 1.12-2.1.1
Forge 14.21.1.2396

**Comment by KidsDontPlay** [comment]
that was a bug in limelib.
fixed in the new version
