### ISSUE TITLE
Removal method

### ISSUE THREAD

**Issue by wizard1399** [KidsDontPlay/Furnus#26]
Hello,
I am using the 1.10.2 version of your mod in a pack I am making and need a means to remove certain recipes that do not show up in the pulvis recipe json. 

Situation I am trying to deal with: in my pack,  dusts melt down to 1.5 ingots worth of liquid. If the player can then take that ingot they just made and grind it into dust, they can remelt it for a profit making a dupe bug. Is there a way to remove just the ingot pulvis recipes? I am using craft tweaker to make all my changes that can not be done via config.

**Comment by KidsDontPlay** [comment]
there is a blacklist for dust in config file. you can insert the dusts that shall not be craftable. e.g. `dustCopper`

**Comment by wizard1399** [comment]
I still want dust from the ores, just not the ingots. I think the config turns both dust from ores and dust from ingots off.
