### ISSUE TITLE
Feature request: always-on IO upgrade

### ISSUE THREAD

**Issue by josephcsible** [KidsDontPlay/Furnus#28]
I don't like the need for an upgrade to pipe items in and out. Can a config setting be added that removes this as an upgrade and just makes it available all the time? (I'd be willing to code this if it would be accepted.)

**Comment by KidsDontPlay** [comment]
furnus/pulvus works like a regular furnace even without IO upgrade.
Means input top, fuel side and output bottom.

**Comment by josephcsible** [comment]
I didn't know that; it is basically all I wanted. The documentation doesn't make that clear at all, though. Can the item be renamed to "Customized IO Upgrade” or something, and have the tooltip (and description on Curse) updated to clarify that?
