### ISSUE TITLE
crashed after placing Pulvus

### ISSUE THREAD

**Issue by LlubNek** [KidsDontPlay/Furnus#3]
Furnus mod crashed after I placed the Pulvus.

Here's the crash report:
http://pastebin.com/hTrWEFAL

**Comment by KidsDontPlay** [comment]
I need more information.
Does it occur every time you place a pulvus?
If yes, would you mind to remove some mods and check if it happen again? (Especially the core mods (top of your crashreport))
Does it happen with furnus too?
Do you play on client or server?
