### ISSUE TITLE
[1.12] crash with forge 2443

### ISSUE THREAD

**Issue by ProCraftLegend** [KidsDontPlay/Furnus#36]
when im trying to load the mod and the limelib with out any other mods it just crashes,.

**Comment by KidsDontPlay** [comment]
crash report?

**Comment by ProCraftLegend** [comment]
Ok

**Comment by ProCraftLegend** [comment]
Is this the owner of the mod

**Comment by ProCraftLegend** [comment]
Yes I’m having an issue where I load the mod and it will crash every time I load it and it’s not with any other mod besides the lime lib mod that goes with it

**Comment by ProCraftLegend** [comment]
I can’t load the crash report when I click to load it it want load don’t know why
