### ISSUE TITLE
Furnus vanilla items being smelted don't stack in outputs + question

### ISSUE THREAD

**Issue by Darkmega18** [KidsDontPlay/Furnus#39]
weird bug. I'm finding wood smelted to charcoal isn't stacking in the output slots. same deal with stone. it also happens now with clay to bricks. I've got this set up. it's got MV power from immersive engineering going into it cause LV burns out of power quickly when smelting full pelt.
Ores and dusts don't seem to have issue being smelted out. but vanilla things're just getting stuck.
![image](https://user-images.githubusercontent.com/8104689/44000914-ce6dcdde-9e6b-11e8-85e7-c9be30626f73.png)

(just a show of something modded being cooked and stacking fine)
![image](https://user-images.githubusercontent.com/8104689/44000951-55ae550c-9e6c-11e8-86fc-c555f48902aa.png)

I'm on a server if thats anything.

secondly, I saw the ability to have external heaters power the furnus and pulvus on the main curse page is crossed out. was it removed due to some development/other reason? Since that is quite a useful way of providing heat that I can't utilize now. :<

**Comment by KidsDontPlay** [comment]
furnus version?
limelib version?
forge version?

**Comment by Darkmega18** [comment]
apologies.

1.12.2 forge ending in 2705
limelib-1.12.2-1.7.12
furnus-1.12.2-2.1.6

all recommended, with the other two being latest available at the time.

**Comment by KidsDontPlay** [comment]
works fine for me.
It's an incompatibility with another mod. but I don't know which one.
You can try to figure it out. Or is it a public modpack?

**Comment by Darkmega18** [comment]
public pack. Called transcendence. What kind of thing would be doing it? what kind of changes would cause this? I'm not sure where to start from honestly. :V
