### ISSUE TITLE
Infinite ingots dupe

### ISSUE THREAD

**Issue by vKakaru** [KidsDontPlay/Furnus#4]
I'd assume this is already known, but there is a way to infinitely dupe iron/gold over and over via the bonus output upgrades. I can re-pulverize an iron ingot, getting more dust, then smelt that in the furnace, with bonus output as well, getting more ingots. Rinse and repeat, over and over. I would assume that is not intentional, but could be mistaken.

-Kakarifers

**Comment by KidsDontPlay** [comment]
this is really dumb. I didn't think about that.
on the other hand bonus upgrades increase the fuel consumption. so you need many coal.
I don't know what to do. Removing the upgrade or just disabling it for the furnus

**Comment by vKakaru** [comment]
The only thing I think you could do that would prevent it is just prevent bonus output from ingots being pulverized. Should solve the issue, no? IE, any ingot pulverized always nets one dust. No exceptions.
